name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: mikewang6700/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
          USERNAME: ${{ github.mikewang6700 }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
